/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.validation;

import org.neclipse.xtext.smalljavadsl.validation.AbstractSmallJavaDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SmallJavaDslValidator extends AbstractSmallJavaDslValidator {
}
