/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.smallJavaDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.ClassType#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getClassType()
 * @model
 * @generated
 */
public interface ClassType extends DataType
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' reference.
   * @see #setType(SmallClazz)
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getClassType_Type()
   * @model
   * @generated
   */
  SmallClazz getType();

  /**
   * Sets the value of the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.ClassType#getType <em>Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' reference.
   * @see #getType()
   * @generated
   */
  void setType(SmallClazz value);

} // ClassType
