/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.smallJavaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Data Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getDataType()
 * @model
 * @generated
 */
public interface DataType extends EObject
{
} // DataType
