/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.smallJavaDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Namespace</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getName <em>Name</em>}</li>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getImportDeclaration <em>Import Declaration</em>}</li>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getSmallClazz <em>Small Clazz</em>}</li>
 * </ul>
 *
 * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getNamespace()
 * @model
 * @generated
 */
public interface Namespace extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getNamespace_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Import Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Import Declaration</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Import Declaration</em>' containment reference.
   * @see #setImportDeclaration(ImportDeclaration)
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getNamespace_ImportDeclaration()
   * @model containment="true"
   * @generated
   */
  ImportDeclaration getImportDeclaration();

  /**
   * Sets the value of the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getImportDeclaration <em>Import Declaration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Import Declaration</em>' containment reference.
   * @see #getImportDeclaration()
   * @generated
   */
  void setImportDeclaration(ImportDeclaration value);

  /**
   * Returns the value of the '<em><b>Small Clazz</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Small Clazz</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Small Clazz</em>' containment reference.
   * @see #setSmallClazz(SmallClazz)
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getNamespace_SmallClazz()
   * @model containment="true"
   * @generated
   */
  SmallClazz getSmallClazz();

  /**
   * Sets the value of the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getSmallClazz <em>Small Clazz</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Small Clazz</em>' containment reference.
   * @see #getSmallClazz()
   * @generated
   */
  void setSmallClazz(SmallClazz value);

} // Namespace
