/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.smallJavaDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslFactory
 * @model kind="package"
 * @generated
 */
public interface SmallJavaDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "smallJavaDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.neclipse.org/xtext/smalljavadsl/SmallJavaDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "smallJavaDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  SmallJavaDslPackage eINSTANCE = org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.NamespaceImpl <em>Namespace</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.NamespaceImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getNamespace()
   * @generated
   */
  int NAMESPACE = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__NAME = 0;

  /**
   * The feature id for the '<em><b>Import Declaration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__IMPORT_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Small Clazz</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE__SMALL_CLAZZ = 2;

  /**
   * The number of structural features of the '<em>Namespace</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NAMESPACE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportDeclarationImpl <em>Import Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportDeclarationImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getImportDeclaration()
   * @generated
   */
  int IMPORT_DECLARATION = 1;

  /**
   * The feature id for the '<em><b>Imports</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_DECLARATION__IMPORTS = 0;

  /**
   * The number of structural features of the '<em>Import Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_DECLARATION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportImpl <em>Import</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getImport()
   * @generated
   */
  int IMPORT = 2;

  /**
   * The feature id for the '<em><b>Imported Namespace</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT__IMPORTED_NAMESPACE = 0;

  /**
   * The number of structural features of the '<em>Import</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPORT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallClazzImpl <em>Small Clazz</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallClazzImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getSmallClazz()
   * @generated
   */
  int SMALL_CLAZZ = 3;

  /**
   * The feature id for the '<em><b>Visibility</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMALL_CLAZZ__VISIBILITY = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMALL_CLAZZ__NAME = 1;

  /**
   * The feature id for the '<em><b>Super Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMALL_CLAZZ__SUPER_CLASS = 2;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMALL_CLAZZ__ATTRIBUTES = 3;

  /**
   * The number of structural features of the '<em>Small Clazz</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SMALL_CLAZZ_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.AttributeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 4;

  /**
   * The feature id for the '<em><b>Datatype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__DATATYPE = 0;

  /**
   * The feature id for the '<em><b>Array</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__ARRAY = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 2;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DataTypeImpl <em>Data Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DataTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getDataType()
   * @generated
   */
  int DATA_TYPE = 5;

  /**
   * The number of structural features of the '<em>Data Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATA_TYPE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BasicTypeImpl <em>Basic Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BasicTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getBasicType()
   * @generated
   */
  int BASIC_TYPE = 6;

  /**
   * The number of structural features of the '<em>Basic Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BASIC_TYPE_FEATURE_COUNT = DATA_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.StringTypeImpl <em>String Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.StringTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getStringType()
   * @generated
   */
  int STRING_TYPE = 7;

  /**
   * The number of structural features of the '<em>String Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BooleanTypeImpl <em>Boolean Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BooleanTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getBooleanType()
   * @generated
   */
  int BOOLEAN_TYPE = 8;

  /**
   * The number of structural features of the '<em>Boolean Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.IntegerTypeImpl <em>Integer Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.IntegerTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getIntegerType()
   * @generated
   */
  int INTEGER_TYPE = 9;

  /**
   * The number of structural features of the '<em>Integer Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INTEGER_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.LongTypeImpl <em>Long Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.LongTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getLongType()
   * @generated
   */
  int LONG_TYPE = 10;

  /**
   * The number of structural features of the '<em>Long Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LONG_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DoubleTypeImpl <em>Double Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DoubleTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getDoubleType()
   * @generated
   */
  int DOUBLE_TYPE = 11;

  /**
   * The number of structural features of the '<em>Double Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DOUBLE_TYPE_FEATURE_COUNT = BASIC_TYPE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ClassTypeImpl <em>Class Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ClassTypeImpl
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getClassType()
   * @generated
   */
  int CLASS_TYPE = 12;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_TYPE__TYPE = DATA_TYPE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Class Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_TYPE_FEATURE_COUNT = DATA_TYPE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility <em>Visibility</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getVisibility()
   * @generated
   */
  int VISIBILITY = 13;


  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace <em>Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Namespace</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace
   * @generated
   */
  EClass getNamespace();

  /**
   * Returns the meta object for the attribute '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getName()
   * @see #getNamespace()
   * @generated
   */
  EAttribute getNamespace_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getImportDeclaration <em>Import Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Import Declaration</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getImportDeclaration()
   * @see #getNamespace()
   * @generated
   */
  EReference getNamespace_ImportDeclaration();

  /**
   * Returns the meta object for the containment reference '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getSmallClazz <em>Small Clazz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Small Clazz</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace#getSmallClazz()
   * @see #getNamespace()
   * @generated
   */
  EReference getNamespace_SmallClazz();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.ImportDeclaration <em>Import Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import Declaration</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.ImportDeclaration
   * @generated
   */
  EClass getImportDeclaration();

  /**
   * Returns the meta object for the containment reference list '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.ImportDeclaration#getImports <em>Imports</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Imports</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.ImportDeclaration#getImports()
   * @see #getImportDeclaration()
   * @generated
   */
  EReference getImportDeclaration_Imports();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Import <em>Import</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Import</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Import
   * @generated
   */
  EClass getImport();

  /**
   * Returns the meta object for the attribute '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Import#getImportedNamespace <em>Imported Namespace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Imported Namespace</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Import#getImportedNamespace()
   * @see #getImport()
   * @generated
   */
  EAttribute getImport_ImportedNamespace();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz <em>Small Clazz</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Small Clazz</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz
   * @generated
   */
  EClass getSmallClazz();

  /**
   * Returns the meta object for the attribute '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getVisibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Visibility</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getVisibility()
   * @see #getSmallClazz()
   * @generated
   */
  EAttribute getSmallClazz_Visibility();

  /**
   * Returns the meta object for the attribute '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getName()
   * @see #getSmallClazz()
   * @generated
   */
  EAttribute getSmallClazz_Name();

  /**
   * Returns the meta object for the reference '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getSuperClass <em>Super Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Super Class</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getSuperClass()
   * @see #getSmallClazz()
   * @generated
   */
  EReference getSmallClazz_SuperClass();

  /**
   * Returns the meta object for the containment reference list '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getAttributes()
   * @see #getSmallClazz()
   * @generated
   */
  EReference getSmallClazz_Attributes();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the containment reference '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute#getDatatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Datatype</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute#getDatatype()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Datatype();

  /**
   * Returns the meta object for the attribute '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute#isArray <em>Array</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Array</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute#isArray()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Array();

  /**
   * Returns the meta object for the attribute '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.DataType <em>Data Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Data Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.DataType
   * @generated
   */
  EClass getDataType();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.BasicType <em>Basic Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Basic Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.BasicType
   * @generated
   */
  EClass getBasicType();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.StringType <em>String Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.StringType
   * @generated
   */
  EClass getStringType();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.BooleanType <em>Boolean Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.BooleanType
   * @generated
   */
  EClass getBooleanType();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.IntegerType <em>Integer Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Integer Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.IntegerType
   * @generated
   */
  EClass getIntegerType();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.LongType <em>Long Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Long Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.LongType
   * @generated
   */
  EClass getLongType();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.DoubleType <em>Double Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Double Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.DoubleType
   * @generated
   */
  EClass getDoubleType();

  /**
   * Returns the meta object for class '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.ClassType <em>Class Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.ClassType
   * @generated
   */
  EClass getClassType();

  /**
   * Returns the meta object for the reference '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.ClassType#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.ClassType#getType()
   * @see #getClassType()
   * @generated
   */
  EReference getClassType_Type();

  /**
   * Returns the meta object for enum '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility <em>Visibility</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Visibility</em>'.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility
   * @generated
   */
  EEnum getVisibility();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  SmallJavaDslFactory getSmallJavaDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.NamespaceImpl <em>Namespace</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.NamespaceImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getNamespace()
     * @generated
     */
    EClass NAMESPACE = eINSTANCE.getNamespace();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NAMESPACE__NAME = eINSTANCE.getNamespace_Name();

    /**
     * The meta object literal for the '<em><b>Import Declaration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAMESPACE__IMPORT_DECLARATION = eINSTANCE.getNamespace_ImportDeclaration();

    /**
     * The meta object literal for the '<em><b>Small Clazz</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NAMESPACE__SMALL_CLAZZ = eINSTANCE.getNamespace_SmallClazz();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportDeclarationImpl <em>Import Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportDeclarationImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getImportDeclaration()
     * @generated
     */
    EClass IMPORT_DECLARATION = eINSTANCE.getImportDeclaration();

    /**
     * The meta object literal for the '<em><b>Imports</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPORT_DECLARATION__IMPORTS = eINSTANCE.getImportDeclaration_Imports();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportImpl <em>Import</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ImportImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getImport()
     * @generated
     */
    EClass IMPORT = eINSTANCE.getImport();

    /**
     * The meta object literal for the '<em><b>Imported Namespace</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IMPORT__IMPORTED_NAMESPACE = eINSTANCE.getImport_ImportedNamespace();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallClazzImpl <em>Small Clazz</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallClazzImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getSmallClazz()
     * @generated
     */
    EClass SMALL_CLAZZ = eINSTANCE.getSmallClazz();

    /**
     * The meta object literal for the '<em><b>Visibility</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMALL_CLAZZ__VISIBILITY = eINSTANCE.getSmallClazz_Visibility();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SMALL_CLAZZ__NAME = eINSTANCE.getSmallClazz_Name();

    /**
     * The meta object literal for the '<em><b>Super Class</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SMALL_CLAZZ__SUPER_CLASS = eINSTANCE.getSmallClazz_SuperClass();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SMALL_CLAZZ__ATTRIBUTES = eINSTANCE.getSmallClazz_Attributes();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.AttributeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Datatype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__DATATYPE = eINSTANCE.getAttribute_Datatype();

    /**
     * The meta object literal for the '<em><b>Array</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__ARRAY = eINSTANCE.getAttribute_Array();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DataTypeImpl <em>Data Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DataTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getDataType()
     * @generated
     */
    EClass DATA_TYPE = eINSTANCE.getDataType();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BasicTypeImpl <em>Basic Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BasicTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getBasicType()
     * @generated
     */
    EClass BASIC_TYPE = eINSTANCE.getBasicType();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.StringTypeImpl <em>String Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.StringTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getStringType()
     * @generated
     */
    EClass STRING_TYPE = eINSTANCE.getStringType();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BooleanTypeImpl <em>Boolean Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.BooleanTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getBooleanType()
     * @generated
     */
    EClass BOOLEAN_TYPE = eINSTANCE.getBooleanType();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.IntegerTypeImpl <em>Integer Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.IntegerTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getIntegerType()
     * @generated
     */
    EClass INTEGER_TYPE = eINSTANCE.getIntegerType();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.LongTypeImpl <em>Long Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.LongTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getLongType()
     * @generated
     */
    EClass LONG_TYPE = eINSTANCE.getLongType();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DoubleTypeImpl <em>Double Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.DoubleTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getDoubleType()
     * @generated
     */
    EClass DOUBLE_TYPE = eINSTANCE.getDoubleType();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ClassTypeImpl <em>Class Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.ClassTypeImpl
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getClassType()
     * @generated
     */
    EClass CLASS_TYPE = eINSTANCE.getClassType();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS_TYPE__TYPE = eINSTANCE.getClassType_Type();

    /**
     * The meta object literal for the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility <em>Visibility</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility
     * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.impl.SmallJavaDslPackageImpl#getVisibility()
     * @generated
     */
    EEnum VISIBILITY = eINSTANCE.getVisibility();

  }

} //SmallJavaDslPackage
