/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.smallJavaDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Small Clazz</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getVisibility <em>Visibility</em>}</li>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getName <em>Name</em>}</li>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getSuperClass <em>Super Class</em>}</li>
 *   <li>{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getAttributes <em>Attributes</em>}</li>
 * </ul>
 *
 * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getSmallClazz()
 * @model
 * @generated
 */
public interface SmallClazz extends EObject
{
  /**
   * Returns the value of the '<em><b>Visibility</b></em>' attribute.
   * The literals are from the enumeration {@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Visibility</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Visibility</em>' attribute.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility
   * @see #setVisibility(Visibility)
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getSmallClazz_Visibility()
   * @model
   * @generated
   */
  Visibility getVisibility();

  /**
   * Sets the value of the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getVisibility <em>Visibility</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Visibility</em>' attribute.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.Visibility
   * @see #getVisibility()
   * @generated
   */
  void setVisibility(Visibility value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getSmallClazz_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Super Class</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Super Class</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Class</em>' reference.
   * @see #setSuperClass(SmallClazz)
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getSmallClazz_SuperClass()
   * @model
   * @generated
   */
  SmallClazz getSuperClass();

  /**
   * Sets the value of the '{@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallClazz#getSuperClass <em>Super Class</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Class</em>' reference.
   * @see #getSuperClass()
   * @generated
   */
  void setSuperClass(SmallClazz value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link org.neclipse.xtext.smalljavadsl.smallJavaDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see org.neclipse.xtext.smalljavadsl.smallJavaDsl.SmallJavaDslPackage#getSmallClazz_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

} // SmallClazz
