/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl;

import org.neclipse.xtext.smalljavadsl.AbstractSmallJavaDslRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallJavaDslRuntimeModule extends AbstractSmallJavaDslRuntimeModule {
}
