/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl;

import org.neclipse.xtext.smalljavadsl.SmallJavaDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SmallJavaDslStandaloneSetup extends SmallJavaDslStandaloneSetupGenerated {
  public static void doSetup() {
    SmallJavaDslStandaloneSetup _smallJavaDslStandaloneSetup = new SmallJavaDslStandaloneSetup();
    _smallJavaDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
