/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SmallJavaDslRuntimeModule extends AbstractSmallJavaDslRuntimeModule {
}
