/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SmallJavaDslStandaloneSetup extends SmallJavaDslStandaloneSetupGenerated {

	def static void doSetup() {
		new SmallJavaDslStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
