/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.neclipse.xtext.smalljavadsl.smallJavaDsl.Namespace

@RunWith(XtextRunner)
@InjectWith(SmallJavaDslInjectorProvider)
class SmallJavaDslParsingTest{

	@Inject
	ParseHelper<Namespace> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			namespace org.neclipse.model
			
			public clazz Customer {
				
			}
		''')
		Assert.assertNotNull(result)
	}

}
