/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.neclipse.xtext.smalljavadsl.scoping;

import org.neclipse.xtext.smalljavadsl.scoping.AbstractSmallJavaDslScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SmallJavaDslScopeProvider extends AbstractSmallJavaDslScopeProvider {
}
